### ISSUE TITLE
[Bug] TypeError: Object of type Spec is not JSON serializable

### ISSUE THREAD

**Issue by oalexandere** [huge-success/sanic-openapi#155] opened 2020-01-08 09:29 UTC
**Description**
Trying to reproduce simple example with Getting Started code: https://sanic-openapi.readthedocs.io/en/latest/
When opens swager page see an error: Failed to load API definition.
With previous version sanic-openapi 0.6.0 everithing works fine.

**Screenshot**
![image](https://user-images.githubusercontent.com/25843869/71966203-364c6d80-3212-11ea-9146-488295b7d8d3.png)

**To Reproduce**

```
from sanic import Sanic
from sanic.response import json
from sanic_openapi import swagger_blueprint

app = Sanic()
app.blueprint(swagger_blueprint)


@app.route("/")
async def test(request):
    return json({"hello": "world"})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
```

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - Python: 3.7
 - Browser: chrome 79.0.3948.88
 - sanic-openapi: 0.6.1
 - sanic: 19.12.2

**Additional context**

> Traceback (most recent call last):
>   File "C:\Users\user\.virtualenvs\bbscreener\lib\site-packages\sanic\app.py", line 974, in handle_request
>     response = handler(request, *args, **kwargs)
>   File "C:\Users\user\.virtualenvs\bbscreener\lib\site-packages\sanic_openapi\swagger.py", line 263, in spec
>     return json(swagger_blueprint._spec)
>   File "C:\Users\user\.virtualenvs\bbscreener\lib\site-packages\sanic\response.py", line 234, in json
>     dumps(body, **kwargs),
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
>     **kw).encode(obj)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
>     chunks = self.iterencode(o, _one_shot=True)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
>     return _iterencode(o, 0)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
>     raise TypeError(f'Object of type {o.__class__.__name__} '
> TypeError: Object of type Spec is not JSON serializable

**Comment by AtomsForPeace** [comment] 2020-01-08 09:39
Thanks for the good bug report. I'll take a look at this later on.

**Comment by AtomsForPeace** [comment] 2020-01-08 18:02
I'm not able to reproduce this locally. What address are you going to?
Works for me at http://localhost:8000/swagger/#/default/test

**Comment by oalexandere** [comment] 2020-01-09 05:55
Hello!
For reproducing I've create a new virtual env and installed only sanic-openapi:
![image](https://user-images.githubusercontent.com/25843869/72041213-fcd03c80-32bb-11ea-8d4b-83e20cebc822.png)

Then run the app:
![image](https://user-images.githubusercontent.com/25843869/72041318-4caf0380-32bc-11ea-88a7-3d3d0c58f035.png)

Goes http://127.0.0.1:8000/ and get {"hello":"world"}. But http://127.0.0.1:8000/swagger/ gets me an error:
![image](https://user-images.githubusercontent.com/25843869/72041405-90a20880-32bc-11ea-8fdc-46aab8e8c4d5.png)

Here is the app errors when I goes to http://127.0.0.1:8000/swagger/:
![image](https://user-images.githubusercontent.com/25843869/72041522-d9f25800-32bc-11ea-9f2a-78f2e038ca50.png)

If I goes http://localhost:8000/swagger/#/default/test it also returns same errors:
![image](https://user-images.githubusercontent.com/25843869/72041788-87656b80-32bd-11ea-8d5c-a644f603de87.png)
![image](https://user-images.githubusercontent.com/25843869/72041773-7d436d00-32bd-11ea-97c0-6ed690fcf788.png)

**Comment by oalexandere** [comment] 2020-01-09 05:58
If downgrade sanic-openapi version to 0.6 everything works fine:
![image](https://user-images.githubusercontent.com/25843869/72041974-15415680-32be-11ea-9897-72ec720b672a.png)
![image](https://user-images.githubusercontent.com/25843869/72042016-373ad900-32be-11ea-9d76-26bd9dfacad8.png)

**Comment by oalexandere** [comment] 2020-01-09 06:52
Additional info, maybe it will be usefull.
Line 263 in swagger.py returns json(swagger_blueprint._spec), where swagger_blueprint._spec is Spec object, not dict as in version 0.6.0 sanic-openapi (rigth screen, line 289):
![image](https://user-images.githubusercontent.com/25843869/72044749-ae27a000-32c5-11ea-9cf5-b64247ac7ca2.png)

**Comment by chenjr0719** [comment] 2020-01-09 07:29
It is because that `ujson` can dump `Spec` class to JSON but `json` can not. And your OS is windows so you can only use `json`. That is the reason I and @AtomsForPeace can not reproducible the bug. Let me think about how to fix it and thanks for your report. It is very helpful to improve this project. :grinning:

**Comment by AtomsForPeace** [comment] 2020-01-09 07:40
@chenjr0719 Can we add CI for windows?

Maybe returning the json of the __dict__ of the Spec class. I could try that but can't really test it... :/

**Comment by oalexandere** [comment] 2020-01-09 08:01
Thank you for your response, I created a pull request with trying to fix it, look it please.

**Comment by chenjr0719** [comment] 2020-01-10 04:04
> @chenjr0719 Can we add CI for windows?

Maybe we can follow the same configuration from [sanic](https://github.com/huge-success/sanic/blob/784d5cce5234933a5af36b668c8ffce1af4af91a/tox.ini#L6-L8) to test without `ujson`. What do you think?

**Comment by chenjr0719** [comment] 2020-01-14 10:47
The #157 has been merged. Close this issue.

**Closed by chenjr0719** 2020-01-14 10:47 UTC

**Comment by xnuinside** [comment] 2020-04-11 11:28
btw, same issue 1-to-1 with 0.6.1 on MacOS 10.14.6, not only on Windows. Also solved problem with downgrade to 0.6.0 version.

**Comment by Ronserruya** [comment] 2020-04-13 13:34
^^ Same issue on MacOs 10.15.1 , works when downgrading to 0.6.0

**Comment by ray-t1** [comment] 2020-05-04 15:18
I'm facing this issue on a local Ubuntu 19.04 env. Tried to downgrade to 0.6.0 but still, have any clue??

**Comment by chenjr0719** [comment] 2020-05-05 04:47
@ray-t1 I think it is related to the new `ujson` release. Would you please try `ujson==1.3.5` and check is this issue still exist? Somehow the new version of `ujson` changes its behavior and it affects the JSON serialization.

**Comment by GitHubLeoYeh** [comment] 2020-05-06 04:22
After install ujson==1.3.5 
Solve it!! 
(Ubuntu 18.04.4 LTS ) 
thanks @chenjr0719

**Comment by dnutiu** [comment] 2020-07-21 14:13
I can confirm that this bug is still happening; Downgrading to usjon==1.35 is not a solution, make silent bugs and memory leaks can occur. usjon==3.0.0 make the de-serialization stricter that's why exceptions occur, errors are no longer ignored.
